# docker-compose.yml
version: '3.8'

services:
  gohtml-server:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s